### ISSUE TITLE
Initial tracking

### ISSUE THREAD

**Issue by jenny-donnelly** [pokeslab/website#3]
- [ ] Allow users to check off items
- [ ] Persist checked items in local storage
- [ ] Persist checked items in Firebase ( #4 )
